const API_ERROR_CODE = {
  DEFAULT_EXCEPTION: "DefaultBusinessErrorCode",
  VALIDATION_EXCEPTION: "ValidationFailed",
  UNAUTHORIZED_EXCEPTION: "Unauthorized",
  NOT_FOUND_EXCEPTION: "NotFound",
  DUPLICATE_EXCEPTION: "Duplicate",
  CONFLICT_EXCEPTION: "Conflict",
  LIMIT_EXCEEDED_EXCEPTION: "LimitExceeded",
  TIME_LIMIT_EXCEPTION: "TimeLimit",
  PERMISSION_DENIED_EXCEPTION: "PermissionDenied",
  BAD_CREDENTIALS_EXCEPTION: "BadCredentials",
  OPERATION_NOT_ALLOWED_EXCEPTION: "OperationNotAllowed",
  SERVICE_UNAVAILABLE_EXCEPTION: "ServiceUnavailable",
  NOT_PROPERLY_EXECUTED_EXCEPTION: "Fail",
  EXPIRED_TOKEN_EXCEPTION: "ExpiredToken",
  INVALID_JWT_SIGNATURE_EXCEPTION: "InvalidJwtSignature",
  EXPIRED_CONNECT_EXCEPTION: "ExpiredConnectionWithFacade",
  FAILED_ENCRYPT_EXCEPTION: "FailedEncrypt",
  REQUIRES_SIGN_UP_EXCEPTION: "RequiresSignUp",
  ILLEGAL_ACCESS_EXCEPTION: "IllegalAccess",
}

export default API_ERROR_CODE
