import { Booking_sidebar, Seat_class } from "../types/booking"

export const MOCK_VIP_SEATS: Seat_class[] = [
  { seatId: 1, row: "A", col: "1", seatGrade: "VIP", booked: true },
  { seatId: 2, row: "A", col: "2", seatGrade: "VIP", booked: true },
  { seatId: 3, row: "A", col: "3", seatGrade: "VIP", booked: true },
  { seatId: 4, row: "A", col: "4", seatGrade: "VIP", booked: true },
  { seatId: 5, row: "A", col: "5", seatGrade: "VIP", booked: true },
  { seatId: 6, row: "A", col: "6", seatGrade: "VIP", booked: true },
  { seatId: 7, row: "A", col: "7", seatGrade: "VIP", booked: true },
  { seatId: 8, row: "A", col: "8", seatGrade: "VIP", booked: true },
  { seatId: 9, row: "A", col: "9", seatGrade: "VIP", booked: true },
  { seatId: 10, row: "A", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 11, row: "B", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 12, row: "B", col: "2", seatGrade: "VIP", booked: true },
  { seatId: 13, row: "B", col: "3", seatGrade: "VIP", booked: true },
  { seatId: 14, row: "B", col: "4", seatGrade: "VIP", booked: true },
  { seatId: 15, row: "B", col: "5", seatGrade: "VIP", booked: true },
  { seatId: 16, row: "B", col: "6", seatGrade: "VIP", booked: false },
  { seatId: 17, row: "B", col: "7", seatGrade: "VIP", booked: true },
  { seatId: 18, row: "B", col: "8", seatGrade: "VIP", booked: true },
  { seatId: 19, row: "B", col: "9", seatGrade: "VIP", booked: true },
  { seatId: 20, row: "B", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 21, row: "C", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 22, row: "C", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 23, row: "C", col: "3", seatGrade: "VIP", booked: false },
  { seatId: 24, row: "C", col: "4", seatGrade: "VIP", booked: false },
  { seatId: 25, row: "C", col: "5", seatGrade: "VIP", booked: false },
  { seatId: 26, row: "C", col: "6", seatGrade: "VIP", booked: false },
  { seatId: 27, row: "C", col: "7", seatGrade: "VIP", booked: false },
  { seatId: 28, row: "C", col: "8", seatGrade: "VIP", booked: false },
  { seatId: 29, row: "C", col: "9", seatGrade: "VIP", booked: true },
  { seatId: 30, row: "C", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 31, row: "D", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 32, row: "D", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 33, row: "D", col: "3", seatGrade: "VIP", booked: false },
  { seatId: 34, row: "D", col: "4", seatGrade: "VIP", booked: false },
  { seatId: 35, row: "D", col: "5", seatGrade: "VIP", booked: false },
  { seatId: 36, row: "D", col: "6", seatGrade: "VIP", booked: false },
  { seatId: 37, row: "D", col: "7", seatGrade: "VIP", booked: false },
  { seatId: 38, row: "D", col: "8", seatGrade: "VIP", booked: true },
  { seatId: 39, row: "D", col: "9", seatGrade: "VIP", booked: false },
  { seatId: 40, row: "D", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 41, row: "E", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 42, row: "E", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 43, row: "E", col: "3", seatGrade: "VIP", booked: false },
  { seatId: 44, row: "E", col: "4", seatGrade: "VIP", booked: false },
  { seatId: 45, row: "E", col: "5", seatGrade: "VIP", booked: false },
  { seatId: 46, row: "E", col: "6", seatGrade: "VIP", booked: false },
  { seatId: 47, row: "E", col: "7", seatGrade: "VIP", booked: false },
  { seatId: 48, row: "E", col: "8", seatGrade: "VIP", booked: false },
  { seatId: 49, row: "E", col: "9", seatGrade: "VIP", booked: false },
  { seatId: 50, row: "E", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 51, row: "F", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 52, row: "F", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 53, row: "F", col: "3", seatGrade: "VIP", booked: false },
  { seatId: 54, row: "F", col: "4", seatGrade: "VIP", booked: false },
  { seatId: 55, row: "F", col: "5", seatGrade: "VIP", booked: false },
  { seatId: 56, row: "F", col: "6", seatGrade: "VIP", booked: false },
  { seatId: 57, row: "F", col: "7", seatGrade: "VIP", booked: false },
  { seatId: 58, row: "F", col: "8", seatGrade: "VIP", booked: false },
  { seatId: 59, row: "F", col: "9", seatGrade: "VIP", booked: false },
  { seatId: 60, row: "F", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 61, row: "G", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 62, row: "G", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 63, row: "G", col: "3", seatGrade: "VIP", booked: false },
  { seatId: 64, row: "G", col: "4", seatGrade: "VIP", booked: false },
  { seatId: 65, row: "G", col: "5", seatGrade: "VIP", booked: false },
  { seatId: 66, row: "G", col: "6", seatGrade: "VIP", booked: false },
  { seatId: 67, row: "G", col: "7", seatGrade: "VIP", booked: false },
  { seatId: 68, row: "G", col: "8", seatGrade: "VIP", booked: false },
  { seatId: 69, row: "G", col: "9", seatGrade: "VIP", booked: true },
  { seatId: 70, row: "G", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 71, row: "H", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 72, row: "H", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 73, row: "H", col: "3", seatGrade: "VIP", booked: false },
  { seatId: 74, row: "H", col: "4", seatGrade: "VIP", booked: false },
  { seatId: 75, row: "H", col: "5", seatGrade: "VIP", booked: false },
  { seatId: 76, row: "H", col: "6", seatGrade: "VIP", booked: true },
  { seatId: 77, row: "H", col: "7", seatGrade: "VIP", booked: false },
  { seatId: 78, row: "H", col: "8", seatGrade: "VIP", booked: false },
  { seatId: 79, row: "H", col: "9", seatGrade: "VIP", booked: true },
  { seatId: 80, row: "H", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 81, row: "I", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 82, row: "I", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 83, row: "I", col: "3", seatGrade: "VIP", booked: false },
  { seatId: 84, row: "I", col: "4", seatGrade: "VIP", booked: false },
  { seatId: 85, row: "I", col: "5", seatGrade: "VIP", booked: false },
  { seatId: 86, row: "I", col: "6", seatGrade: "VIP", booked: false },
  { seatId: 87, row: "I", col: "7", seatGrade: "VIP", booked: false },
  { seatId: 88, row: "I", col: "8", seatGrade: "VIP", booked: true },
  { seatId: 89, row: "I", col: "9", seatGrade: "VIP", booked: true },
  { seatId: 90, row: "I", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 91, row: "J", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 92, row: "J", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 93, row: "J", col: "3", seatGrade: "VIP", booked: false },
  { seatId: 94, row: "J", col: "4", seatGrade: "VIP", booked: false },
  { seatId: 95, row: "J", col: "5", seatGrade: "VIP", booked: false },
  { seatId: 96, row: "J", col: "6", seatGrade: "VIP", booked: false },
  { seatId: 97, row: "J", col: "7", seatGrade: "VIP", booked: true },
  { seatId: 98, row: "J", col: "8", seatGrade: "VIP", booked: true },
  { seatId: 99, row: "J", col: "9", seatGrade: "VIP", booked: true },
  { seatId: 100, row: "J", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 101, row: "K", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 102, row: "K", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 103, row: "K", col: "3", seatGrade: "VIP", booked: false },
  { seatId: 104, row: "K", col: "4", seatGrade: "VIP", booked: false },
  { seatId: 105, row: "K", col: "5", seatGrade: "VIP", booked: true },
  { seatId: 106, row: "K", col: "6", seatGrade: "VIP", booked: false },
  { seatId: 107, row: "K", col: "7", seatGrade: "VIP", booked: true },
  { seatId: 108, row: "K", col: "8", seatGrade: "VIP", booked: true },
  { seatId: 109, row: "K", col: "9", seatGrade: "VIP", booked: true },
  { seatId: 110, row: "K", col: "10", seatGrade: "VIP", booked: true },

  { seatId: 111, row: "L", col: "1", seatGrade: "VIP", booked: false },
  { seatId: 112, row: "L", col: "2", seatGrade: "VIP", booked: false },
  { seatId: 113, row: "L", col: "3", seatGrade: "VIP", booked: true },
  { seatId: 114, row: "L", col: "4", seatGrade: "VIP", booked: true },
  { seatId: 115, row: "L", col: "5", seatGrade: "VIP", booked: true },
  { seatId: 116, row: "L", col: "6", seatGrade: "VIP", booked: true },
  { seatId: 117, row: "L", col: "7", seatGrade: "VIP", booked: true },
  { seatId: 118, row: "L", col: "8", seatGrade: "VIP", booked: true },
  { seatId: 119, row: "L", col: "9", seatGrade: "VIP", booked: true },
  { seatId: 120, row: "L", col: "10", seatGrade: "VIP", booked: true },
]

export const MOCK_BOOKING_DATA: Booking_sidebar = {
  eventScheduleId: 1,
  remainingSeatsByGrade: [
    {
      seatGrade: "VIP",
      remainingSeats: 95,
      price: 198000,
    },
    {
      seatGrade: "R",
      remainingSeats: 0,
      price: 178000,
    },
    {
      seatGrade: "A",
      remainingSeats: 0,
      price: 148000,
    },
    {
      seatGrade: "B",
      remainingSeats: 0,
      price: 128000,
    },
  ],
}
